language: cpp

sudo: false

addons:
 apt:
  packages:
  # install i386 base libraries for the NaCl toolchain (parts of which are
  # 32-bit) as well as the regal linux build deps.
  - libc6:i386
  - libstdc++6:i386
  - libglib2.0-0:i386
  - libxmu-dev
  - libxi-dev

script:
 - scripts/travis-build.sh

install:
 - scripts/travis-install.sh

env:
 - SYSTEM=linux
 - SYSTEM=nacl-i686
 - SYSTEM=nacl-x86_64
 - SYSTEM=nacl-arm
 - MODE=debug SYSTEM=linux
 - MODE=debug SYSTEM=nacl-i686
 - MODE=debug SYSTEM=nacl-x86_64
 - MODE=debug SYSTEM=nacl-arm
