NAME = $(REGAL_NAME)

CC   := emcc
CXX  := em++
LD   := emcc
AR   := emar

ifdef EMSCRIPTEN
CC   := $(EMSCRIPTEN)/$(CC)
CXX  := $(EMSCRIPTEN)/$(CXX)
LD   := $(EMSCRIPTEN)/$(LD)
AR   := $(EMSCRIPTEN)/$(AR)
endif

OBJDUMP := /bin/false
RANLIB :=
STRIP :=
LN :=

BIN.SUFFIX = .html
EXT.DYNAMIC = js

CFLAGS.DEBUG   = -O2
CFLAGS.RELEASE = -O2

#LIB.SHARED = lib$(NAME).js
LIB.STATIC = lib$(NAME).a

LDFLAGS.DEBUG  += -g
LDFLAGS.EXTRA  += -s DISABLE_GL_EMULATION=1 -O2
LDFLAGS.SO     += -s SIDE_MODULE=1
